<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Generator as Faker;

class ReviewsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(Faker $faker): void
    {

        $persReviews = [
            ["doctor_id" => 1, "rating" => 5, "text" => "Un medico fantastico, mi ha accolto con un sorriso e mi ha ascoltato attentamente. Ha fatto una visita accurata e mi ha spiegato tutto con parole semplici. Mi ha dato dei consigli utili e mi ha rassicurato. Lo consiglio vivamente a tutti."], ["doctor_id" => 1, "rating" => 5, "text" => "Ha salvato la vita a mio figlio, che era in gravi condizioni. Ha agito con prontezza e professionalità, dimostrando una grande competenza. Ha seguito il caso con dedizione e ha mantenuto un contatto costante con me. Gli sarò sempre grato, è un angelo."], ["doctor_id" => 1, "rating" => 5, "text" => "Grazie di cuore, dottore. Lei è stato gentilissimo e paziente con me. Ha capito il mio problema e mi ha aiutato a risolverlo. Ha fatto un lavoro eccellente e mi ha restituito la salute. Non ho parole per ringraziarla, è il migliore."], ["doctor_id" => 2, "rating" => 2, "text" => "Non mi ha ascoltato bene, mi ha interrotto più volte e non ha capito le mie esigenze. Ha fatto una visita superficiale e mi ha prescritto dei farmaci che non mi hanno fatto effetto. Mi ha dato l'impressione di essere poco interessato e poco preparato."], ["doctor_id" => 2, "rating" => 1, "text" => "Mi ha fatto male con l'ago, mi ha provocato un'emorragia e non si è scusato. Mi ha trattato con arroganza e maleducazione, facendomi sentire in colpa. Mi ha fatto delle domande inappropriate e mi ha giudicato. È stato il peggior medico che abbia mai incontrato."], ["doctor_id" => 2, "rating" => 2, "text" => "Non tornerò mai più da lui, mi ha deluso tantissimo. Ha sbagliato la diagnosi e mi ha fatto perdere tempo prezioso. Ha dimostrato di non essere aggiornato sulle ultime scoperte scientifiche e di non avere esperienza. Mi ha fatto pagare troppo per una prestazione scadente."], ["doctor_id" => 3, "rating" => 3, "text" => "Un medico normale, non mi ha entusiasmato ma neanche deluso. Ha fatto il suo lavoro in modo corretto ma senza brillare. Mi ha dato delle spiegazioni sufficienti ma non esaustive. Mi ha dato dei farmaci efficaci ma non innovativi. Non mi ha fatto né bene né male."], ["doctor_id" => 3, "rating" => 4, "text" => "Ha fatto il suo lavoro in modo soddisfacente, dimostrando professionalità e competenza. Mi ha visitato con cura e mi ha dato delle indicazioni chiare. Mi ha seguito con attenzione e mi ha risposto a tutte le domande. Mi ha fatto sentire a mio agio e mi ha tranquillizzato."], ["doctor_id" => 3, "rating" => 3, "text" => "Non mi ha entusiasmato, ma neanche deluso. Ha fatto una visita veloce ma accurata, mi ha dato delle informazioni utili ma non approfondite. Mi ha dato dei farmaci generici ma efficaci. Non mi ha fatto sentire speciale ma neanche trascurato."],
            ["doctor_id" => 4, "rating" => 1, "text" => "Un medico orribile, mi ha fatto una visita pessima e mi ha dato dei farmaci sbagliati. Mi ha causato delle complicazioni e non si è fatto più sentire. Ha dimostrato di essere inesperto e negligente. Mi ha rovinato la vita."], ["doctor_id" => 4, "rating" => 1, "text" => "Ha sbagliato tutto, mi ha diagnosticato una malattia che non avevo e mi ha sottoposto a delle cure inutili. Mi ha fatto soffrire inutilmente e non ha ammesso i suoi errori. Ha dimostrato di essere incompetente e irresponsabile. Mi ha fatto un danno enorme."], ["doctor_id" => 4, "rating" => 1, "text" => "Mi ha fatto perdere tempo e soldi, mi ha fatto fare delle analisi costose e inutili e mi ha dato dei farmaci scaduti. Mi ha ignorato quando gli ho chiesto delle spiegazioni e mi ha trattato con disprezzo. Ha dimostrato di essere disonesto e scorretto. Mi ha preso in giro."], ["doctor_id" => 5, "rating" => 4, "text" => "Un medico preparato, mi ha fatto una visita approfondita e mi ha dato dei farmaci efficaci. Mi ha risolto il problema e mi ha seguito con cura. Ha dimostrato di essere competente e professionale. Mi ha aiutato molto."], ["doctor_id" => 5, "rating" => 5, "text" => "Ha capito subito il mio problema, mi ha visitato con attenzione e mi ha dato la terapia giusta. Mi ha spiegato tutto con chiarezza e mi ha rassicurato. Ha dimostrato di essere esperto e aggiornato. Mi ha restituito la salute."], ["doctor_id" => 5, "rating" => 4, "text" => "Mi ha dato dei buoni consigli, mi ha visitato con gentilezza e mi ha dato dei farmaci adatti. Mi ha informato su tutto e mi ha ascoltato con pazienza. Ha dimostrato di essere bravo e disponibile. Mi ha fatto sentire bene."], ["doctor_id" => 6, "rating" => 3, "text" => "Un medico discreto, non mi ha entusiasmato ma neanche deluso. Ha fatto il suo lavoro in modo corretto ma senza brillare. Mi ha dato delle spiegazioni sufficienti ma non esaustive. Mi ha dato dei farmaci efficaci ma non innovativi. Non mi ha fatto né bene né male."], ["doctor_id" => 6, "rating" => 2, "text" => "Ha fatto delle domande inutili, mi ha visitato con superficialità e mi ha dato dei farmaci scadenti. Mi ha confuso le idee e mi ha trascurato. Ha dimostrato di essere poco interessato e poco preparato. Mi ha deluso molto."], ["doctor_id" => 6, "rating" => 3, "text" => "Non mi ha deluso ma neanche sorpreso, mi ha visitato con rapidità ma senza trascurare nulla. Mi ha dato delle informazioni utili ma non approfondite. Mi ha dato dei farmaci generici ma efficaci. Non mi ha fatto sentire speciale ma neanche trascurato."],
            ["doctor_id" => 7, "rating" => 5, "text" => "Un medico simpatico, mi ha accolto con un sorriso e mi ha fatto delle battute divertenti. Mi ha visitato con cura e mi ha spiegato tutto con umorismo. Mi ha dato dei consigli utili e mi ha fatto ridere. Lo adoro."], ["doctor_id" => 7, "rating" => 5, "text" => "Ha fatto delle battute divertenti, mi ha visitato con allegria e mi ha dato dei farmaci efficaci. Mi ha spiegato tutto con ironia e mi ha ascoltato con interesse. Mi ha dato dei consigli simpatici e mi ha fatto stare bene. È il mio preferito."], ["doctor_id" => 7, "rating" => 5, "text" => "Mi ha fatto sentire a mio agio, mi ha visitato con gentilezza e mi ha fatto delle battute spiritose. Mi ha spiegato tutto con semplicità e mi ha rassicurato. Mi ha dato dei consigli pratici e mi ha fatto sorridere. È un grande."], ["doctor_id" => 8, "rating" => 2, "text" => "Un medico noioso, mi ha accolto con freddezza e mi ha parlato solo di sé. Mi ha visitato con distacco e mi ha spiegato poco. Mi ha dato dei farmaci scarsi e mi ha ignorato. Non lo sopporto."], ["doctor_id" => 8, "rating" => 1, "text" => "Ha parlato solo di sé, mi ha visitato con disinteresse e mi ha dato dei farmaci sbagliati. Mi ha spiegato niente e mi ha trascurato. Mi ha dato dei consigli inutili e mi ha fatto arrabbiare. È il peggiore."], ["doctor_id" => 8, "rating" => 2, "text" => "Mi ha annoiato a morte, mi ha visitato con superficialità e mi ha dato dei farmaci inutili. Mi ha spiegato male e mi ha confuso. Mi ha dato dei consigli banali e mi ha fatto perdere tempo. Non lo consiglio."], ["doctor_id" => 9, "rating" => 3, "text" => "Un medico strano, mi ha accolto con una smorfia e mi ha fatto delle domande bizzarre. Mi ha visitato con curiosità e mi ha spiegato delle cose stravaganti. Mi ha dato dei farmaci insoliti ma efficaci. Non so cosa pensare di lui."], ["doctor_id" => 9, "rating" => 4, "text" => "Ha fatto delle cose insolite ma efficaci, mi ha visitato con originalità e mi ha dato dei farmaci innovativi. Mi ha spiegato delle cose interessanti e mi ha sorpreso. Mi ha dato dei consigli fuori dal comune ma utili. È un genio."], ["doctor_id" => 9, "rating" => 3, "text" => "Non so cosa pensare di lui, mi ha visitato con metodo e mi ha dato dei farmaci diversi dal solito. Mi ha spiegato delle cose nuove e mi ha incuriosito. Mi ha dato dei consigli strani ma funzionali. È un originale."],
            ["rating" => 4, "text" => "Un medico serio, mi ha accolto con rispetto e mi ha ascoltato attentamente. Mi ha visitato con competenza e mi ha spiegato tutto con chiarezza. Mi ha dato dei consigli utili e mi ha seguito con cura. Lo apprezzo molto."], ["rating" => 5, "text" => "Ha fatto un'ottima visita, mi ha visitato con professionalità e mi ha dato dei farmaci efficaci. Mi ha spiegato tutto con precisione e mi ha rassicurato. Mi ha dato dei consigli pratici e mi ha restituito la salute. Lo ringrazio di cuore."], ["rating" => 4, "text" => "Mi ha dato delle spiegazioni chiare, mi ha visitato con gentilezza e mi ha dato dei farmaci adatti. Mi ha spiegato tutto con semplicità e mi ha ascoltato con pazienza. Mi ha dato dei consigli validi e mi ha aiutato a risolvere il problema. Lo consiglio vivamente."], ["rating" => 1, "text" => "Un medico inaffidabile, mi ha accolto con indifferenza e non mi ha ascoltato. Mi ha visitato con superficialità e mi ha dato dei farmaci scaduti. Mi ha spiegato poco e male e non si è fatto più sentire. Lo sconsiglio fortemente."], ["rating" => 1, "text" => "Ha cancellato l'appuntamento all'ultimo minuto, mi ha fatto perdere tempo e soldi. Non si è scusato e non mi ha dato una spiegazione. Non si è fatto più vedere e non ha risposto alle mie chiamate. È stato un comportamento vergognoso."], ["rating" => 1, "text" => "Mi ha trattato con sufficienza, mi ha visitato con arroganza e mi ha dato dei farmaci sbagliati. Mi ha spiegato niente e non mi ha ascoltato. Mi ha causato delle complicazioni e non si è fatto carico della situazione. È stato un disastro."], ["rating" => 3, "text" => "Un medico onesto, mi ha accolto con cordialità e mi ha ascoltato con interesse. Mi ha visitato con correttezza e mi ha spiegato tutto con onestà. Mi ha dato dei consigli utili e mi ha seguito con discrezione. Non ho nulla da ridire."], ["rating" => 2, "text" => "Ha fatto il suo dovere ma senza entusiasmo, mi ha visitato con fretta e mi ha dato dei farmaci generici. Mi ha spiegato poco e in modo confuso. Mi ha dato dei consigli banali e non si è interessato al mio caso. Non mi ha soddisfatto."], ["rating" => 3, "text" => "Non mi ha chiesto nulla di me, mi ha visitato con distacco e mi ha dato dei farmaci efficaci ma non innovativi. Mi ha spiegato tutto in modo sufficiente ma non approfondito. Mi ha dato dei consigli standard e non si è personalizzato il servizio. Non mi ha entusiasmato."],

            ["rating" => 2, "text" => "Un medico scostante, mi ha visitato con freddezza e mi ha dato dei farmaci scarsi. Mi ha spiegato poco e male e non mi ha ascoltato. Mi ha deluso molto."], ["rating" => 1, "text" => "Ha fatto male il suo lavoro, mi ha visitato con superficialità e mi ha dato dei farmaci sbagliati. Mi ha spiegato niente e non mi ha ascoltato. Mi ha rovinato la vita."], ["rating" => 2, "text" => "Mi ha fatto sentire a disagio, mi ha visitato con maleducazione e mi ha dato dei farmaci inutili. Mi ha spiegato male e non mi ha ascoltato. Mi ha fatto arrabbiare."], ["rating" => 5, "text" => "Un medico eccezionale, mi ha visitato con professionalità e mi ha dato dei farmaci efficaci. Mi ha spiegato tutto con chiarezza e mi ha ascoltato. Mi ha restituito la salute."], ["rating" => 5, "text" => "Ha capito subito il mio problema, mi ha visitato con competenza e mi ha dato la terapia giusta. Mi ha spiegato tutto con precisione e mi ha ascoltato. Mi ha aiutato molto."], ["rating" => 5, "text" => "Mi ha trattato con gentilezza, mi ha visitato con cura e mi ha dato dei farmaci adatti. Mi ha spiegato tutto con semplicità e mi ha ascoltato. Mi ha fatto sentire bene."], ["rating" => 3, "text" => "Un medico mediocre, non mi ha entusiasmato ma neanche deluso. Ha fatto il suo lavoro in modo corretto ma senza brillare. Mi ha dato dei farmaci efficaci ma non innovativi. Non mi ha fatto né bene né male."], ["rating" => 3, "text" => "Ha fatto una visita veloce, non mi ha entusiasmato ma neanche deluso. Ha fatto il suo lavoro in modo corretto ma senza brillare. Mi ha dato dei farmaci efficaci ma non innovativi. Non mi ha fatto né bene né male."], ["rating" => 3, "text" => "Mi ha dato dei farmaci generici, non mi ha entusiasmato ma neanche deluso. Ha fatto il suo lavoro in modo corretto ma senza brillare. Mi ha dato dei farmaci efficaci ma non innovativi. Non mi ha fatto né bene né male."],
            ["rating" => 4, "text" => "Un medico preparato, mi ha visitato con competenza e mi ha dato dei farmaci efficaci. Mi ha spiegato tutto con chiarezza e mi ha ascoltato. Mi ha risolto il problema."], ["rating" => 5, "text" => "Un medico professionale, mi ha visitato con cura e mi ha dato dei farmaci adatti. Mi ha spiegato tutto con precisione e mi ha ascoltato. Mi ha restituito la salute."], ["rating" => 4, "text" => "Un medico bravo, mi ha visitato con gentilezza e mi ha dato dei farmaci utili. Mi ha spiegato tutto con semplicità e mi ha ascoltato. Mi ha fatto sentire bene."], ["rating" => 1, "text" => "Un medico pessimo, mi ha visitato con superficialità e mi ha dato dei farmaci scaduti. Mi ha spiegato poco e male e non mi ha ascoltato. Mi ha deluso molto."], ["rating" => 1, "text" => "Un medico disastroso, mi ha visitato con disinteresse e mi ha dato dei farmaci sbagliati. Mi ha spiegato niente e non mi ha ascoltato. Mi ha rovinato la vita."], ["rating" => 1, "text" => "Un medico orribile, mi ha visitato con maleducazione e mi ha dato dei farmaci inutili. Mi ha spiegato male e non mi ha ascoltato. Mi ha fatto arrabbiare."], ["rating" => 3, "text" => "Un medico normale, non mi ha entusiasmato ma neanche deluso. Ha fatto il suo lavoro in modo corretto ma senza brillare. Mi ha dato dei farmaci efficaci ma non innovativi. Non mi ha fatto né bene né male."], ["rating" => 3, "text" => "Ha fatto una visita veloce, non mi ha entusiasmato ma neanche deluso. Ha fatto il suo lavoro in modo corretto ma senza brillare. Mi ha dato dei farmaci efficaci ma non innovativi. Non mi ha fatto né bene né male."], ["rating" => 3, "text" => "Mi ha dato dei farmaci generici, non mi ha entusiasmato ma neanche deluso. Ha fatto il suo lavoro in modo corretto ma senza brillare. Mi ha dato dei farmaci efficaci ma non innovativi. Non mi ha fatto né bene né male."],
            ["rating" => 5, "text" => "Un medico fantastico, mi ha visitato con professionalità e mi ha dato dei farmaci efficaci. Mi ha spiegato tutto con chiarezza e mi ha ascoltato. Mi ha restituito la salute."], ["rating" => 5, "text" => "Un medico eccezionale, mi ha visitato con competenza e mi ha dato dei farmaci adatti. Mi ha spiegato tutto con precisione e mi ha ascoltato. Mi ha aiutato molto."], ["rating" => 5, "text" => "Un medico meraviglioso, mi ha visitato con gentilezza e mi ha dato dei farmaci utili. Mi ha spiegato tutto con semplicità e mi ha ascoltato. Mi ha fatto sentire bene."], ["rating" => 2, "text" => "Un medico scadente, mi ha visitato con superficialità e mi ha dato dei farmaci scaduti. Mi ha spiegato poco e male e non mi ha ascoltato. Mi ha deluso molto."], ["rating" => 1, "text" => "Un medico pessimo, mi ha visitato con disinteresse e mi ha dato dei farmaci sbagliati. Mi ha spiegato niente e non mi ha ascoltato. Mi ha rovinato la vita."], ["rating" => 2, "text" => "Un medico mediocre, mi ha visitato con maleducazione e mi ha dato dei farmaci inutili. Mi ha spiegato male e non mi ha ascoltato. Mi ha fatto arrabbiare."], ["rating" => 3, "text" => "Un medico normale, non mi ha entusiasmato ma neanche deluso. Ha fatto il suo lavoro in modo corretto ma senza brillare. Mi ha dato dei farmaci efficaci ma non innovativi. Non mi ha fatto né bene né male."], ["rating" => 3, "text" => "Ha fatto una visita veloce, non mi ha entusiasmato ma neanche deluso. Ha fatto il suo lavoro in modo corretto ma senza brillare. Mi ha dato dei farmaci efficaci ma non innovativi. Non mi ha fatto né bene né male."], ["rating" => 3, "text" => "Mi ha dato dei farmaci generici, non mi ha entusiasmato ma neanche deluso. Ha fatto il suo lavoro in modo corretto ma senza brillare. Mi ha dato dei farmaci efficaci ma non innovativi. Non mi ha fatto né bene né male."],

            ["rating" => 5, "text" => "Un professionista eccezionale, mi ha seguito con cura e competenza"], ["rating" => 4, "text" => "Sono soddisfatta della visita, il dottore è stato gentile e chiaro nelle spiegazioni"], ["rating" => 3, "text" => "La visita è stata abbastanza buona, ma ho dovuto aspettare molto in sala d'attesa"], ["rating" => 2, "text" => "Non mi sono trovata bene con questo dottore, mi ha dato delle indicazioni poco chiare e mi ha fatto sentire a disagio"], ["rating" => 1, "text" => "Una pessima esperienza, il dottore è stato scortese e superficiale, non lo consiglio a nessuno"], ["rating" => 2, "text" => "Il dottore è stato abbastanza preparato, ma non mi ha dato molta fiducia, ho preferito consultare un altro specialista"], ["rating" => 4, "text" => "Un buon dottore, mi ha fatto una visita accurata e mi ha dato dei consigli utili"], ["rating" => 5, "text" => "Sono rimasta molto contenta della visita, il dottore è stato cordiale e professionale, mi ha risolto il problema"], ["rating" => 3, "text" => "La visita è stata sufficiente, ma il dottore mi è sembrato un po' distratto e frettoloso"],
            ["rating" => 1, "text" => "Una visita orribile, il dottore non mi ha ascoltato e mi ha prescritto delle medicine sbagliate"], ["rating" => 2, "text" => "Non mi sono fidata di questo dottore, mi ha fatto delle domande inutili e mi ha fatto pagare troppo"], ["rating" => 1, "text" => "Il peggior dottore che abbia mai incontrato, mi ha trattato male e mi ha fatto male durante la visita"], ["rating" => 3, "text" => "La visita è stata nella media, il dottore è stato educato ma non molto empatico"], ["rating" => 4, "text" => "Ho apprezzato la visita, il dottore è stato bravo e mi ha dato delle rassicurazioni"], ["rating" => 5, "text" => "Un ottimo dottore, mi ha fatto una visita completa e mi ha spiegato tutto con pazienza"], ["rating" => 4, "text" => "Un dottore competente e disponibile, mi ha fatto sentire a mio agio e mi ha dato delle soluzioni efficaci"], ["rating" => 3, "text" => "La visita è stata discreta, il dottore è stato cortese ma un po' sbrigativo"], ["rating" => 4, "text" => "Mi sono trovata bene con questo dottore, mi ha ascoltato con attenzione e mi ha dato delle indicazioni chiare"],
            ["rating" => 5, "text" => "Un dottore fantastico, mi ha curato con professionalità e gentilezza, lo ringrazio di cuore"], ["rating" => 4, "text" => "Sono stata bene con questo dottore, mi ha fatto una visita approfondita e mi ha consigliato bene"], ["rating" => 5, "text" => "Il miglior dottore che abbia mai conosciuto, mi ha salvato la vita con la sua competenza e la sua umanità"], ["rating" => 2, "text" => "Non ho gradito la visita, il dottore è stato freddo e distaccato, mi ha fatto delle domande irrilevanti"], ["rating" => 1, "text" => "Una visita vergognosa, il dottore è stato maleducato e arrogante, mi ha fatto perdere tempo e soldi"], ["rating" => 2, "text" => "Non consiglio questo dottore, mi ha fatto una visita superficiale e mi ha dato delle medicine inutili"], ["rating" => 3, "text" => "La visita è stata decente, il dottore è stato corretto ma non molto coinvolgente"], ["rating" => 4, "text" => "Ho ricevuto una buona visita, il dottore è stato preparato e simpatico, mi ha aiutato a risolvere il mio problema"], ["rating" => 3, "text" => "La visita è stata normale, il dottore è stato onesto ma un po' noioso, non mi ha entusiasmato"],
            ["rating" => 1, "text" => "Una visita da dimenticare, il dottore non ha capito il mio problema e mi ha trattato con sufficienza"], ["rating" => 2, "text" => "Non sono rimasta soddisfatta della visita, il dottore è stato poco professionale e mi ha fatto male"], ["rating" => 1, "text" => "Il dottore è stato inutile e scortese, mi ha fatto delle diagnosi sbagliate e mi ha fatto pagare una cifra esorbitante"], ["rating" => 3, "text" => "La visita è stata mediocre, il dottore è stato educato ma non molto competente"], ["rating" => 4, "text" => "Sono stata contenta della visita, il dottore è stato bravo e mi ha dato delle buone informazioni"], ["rating" => 5, "text" => "Un dottore eccellente, mi ha fatto una visita dettagliata e mi ha spiegato tutto con chiarezza e pazienza"], ["rating" => 4, "text" => "Un dottore valido e serio, mi ha fatto una visita accurata e mi ha prescritto delle terapie efficaci"], ["rating" => 3, "text" => "La visita è stata accettabile, il dottore è stato gentile ma un po' frettoloso"], ["rating" => 4, "text" => "Mi sono trovata bene con questo dottore, mi ha ascoltato con interesse e mi ha dato delle buone soluzioni"],
            ["rating" => 5, "text" => "Un dottore meraviglioso, mi ha curato con professionalità e gentilezza, lo consiglio vivamente"], ["rating" => 4, "text" => "Sono stata bene con questo dottore, mi ha fatto una visita approfondita e mi ha consigliato bene"], ["rating" => 5, "text" => "Il miglior dottore che abbia mai conosciuto, mi ha salvato la vita con la sua competenza e la sua umanità"], ["rating" => 2, "text" => "Non ho gradito la visita, il dottore è stato freddo e distaccato, mi ha fatto delle domande irrilevanti"], ["rating" => 1, "text" => "Una visita vergognosa, il dottore è stato maleducato e arrogante, mi ha fatto perdere tempo e soldi"], ["rating" => 2, "text" => "Non consiglio questo dottore, mi ha fatto una visita superficiale e mi ha dato delle medicine inutili"], ["rating" => 3, "text" => "La visita è stata decente, il dottore è stato corretto ma non molto coinvolgente"], ["rating" => 4, "text" => "Ho ricevuto una buona visita, il dottore è stato preparato e simpatico, mi ha aiutato a risolvere il mio problema"], ["rating" => 3, "text" => "La visita è stata normale, il dottore è stato onesto ma un po' noioso, non mi ha entusiasmato"]







        ];

        for ($i = 1; $i < 100; $i++) {
            for ($x = 1; $x < rand(1,6); $x++) {
                $randreview = array_rand($persReviews);
                $alreadyUsed = [];
                array_push($alreadyUsed, $randreview);
                while (in_array($randreview, $alreadyUsed)) {
                    $randreview = array_rand($persReviews);
                }
            DB::table('reviews')->insert([
                'doctor_id' => $i,
                'email' => $faker->email(),
                'name' => $faker->name(),
                'rating' => $persReviews[$randreview]['rating'],
                'text' => $persReviews[$randreview]['text'],
            ]);

    }}}}








